### ISSUE TITLE
Documentation: where should be declared a Template Provider?

### ISSUE THREAD

**Issue by rapenne-s** [Morfly/airin#3]
hello,

in https://github.com/Morfly/airin/blob/master/docs/airin_gradle_migration.md#step-3---creating-template-providers it's not clear for me where I need to create the template providers, and with which name. Could you add this information to the documentation please? :pray:

**Comment by Morfly** [comment]
Hello,

Thank you for the question!

The templates should be declared in `buildSrc` directory. This will ensure, all of them are available to Gradle during the build phase. Please find an example of such a declared template [here](https://github.com/Morfly/airin/blob/master/examples/migration/android-compose-dagger/buildSrc/src/main/kotlin/AndroidModuleBuild.kt).

As for the naming, it's more a matter of preference. In the example link above, a template provider is called `AndroidModuleBuild`, as it generates a `BUILD` file for all Android modules.

**Comment by Morfly** [comment]
Airin was rebuilt from the ground up in the latest 0.5.2 release.
Please check the updated documentation as well as the [blog post](https://medium.com/turo-engineering/boosting-bazel-adoption-on-android-with-automation-6dc79d298628) about it.

I will close this issue for now, but please feel free to reopen it in case of any issues/questions.
